// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using 캠핑_정보_탐색_프로그램_V1.Data;

#nullable disable

namespace 캠핑_정보_탐색_프로그램_V1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520054513_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("캠핑_정보_탐색_프로그램_V1.Models.Entity.Camp", b =>
                {
                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<string>("Addr1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Addr2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AnimalCmgCl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AutoSiteCo")
                        .HasColumnType("int");

                    b.Property<int>("CaravSiteCo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoNm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FacltNm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FeatureNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GlampSiteCo")
                        .HasColumnType("int");

                    b.Property<int>("GnrlSiteCo")
                        .HasColumnType("int");

                    b.Property<string>("Homepage")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Induty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Intro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LctCl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LineIntro")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<double>("MapX")
                        .HasColumnType("float");

                    b.Property<double>("MapY")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResveUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SbrsCl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SigunguNm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("ContentId");

                    b.ToTable("Camps");
                });

            modelBuilder.Entity("캠핑_정보_탐색_프로그램_V1.Models.Entity.CampItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PerAdultAmount")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CampItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "주거/침구",
                            Name = "텐트 본체 및 플라이",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "동"
                        },
                        new
                        {
                            Id = 2,
                            Category = "주거/침구",
                            Name = "폴대, 팩, 망치 세트",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "세트"
                        },
                        new
                        {
                            Id = 3,
                            Category = "주거/침구",
                            Name = "그라운드시트 (방수포)",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 4,
                            Category = "주거/침구",
                            Name = "타프 (그늘막)",
                            PerAdultAmount = 0.20000000000000001,
                            Unit = "동"
                        },
                        new
                        {
                            Id = 5,
                            Category = "주거/침구",
                            Name = "캠핑 매트 (발포/에어)",
                            PerAdultAmount = 1.0,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 6,
                            Category = "주거/침구",
                            Name = "침낭",
                            PerAdultAmount = 1.0,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 7,
                            Category = "주거/침구",
                            Name = "캠핑용 베개",
                            PerAdultAmount = 1.0,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 8,
                            Category = "주거/침구",
                            Name = "전기매트",
                            PerAdultAmount = 0.5,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 9,
                            Category = "주거/침구",
                            Name = "캠핑 의자",
                            PerAdultAmount = 1.0,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 10,
                            Category = "주거/침구",
                            Name = "캠핑 테이블",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 11,
                            Category = "조명/전기",
                            Name = "메인 랜턴 (고광량)",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 12,
                            Category = "조명/전기",
                            Name = "이너 랜턴 (텐트 내부용)",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 13,
                            Category = "조명/전기",
                            Name = "감성 무드 랜턴",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 14,
                            Category = "조명/전기",
                            Name = "헤드 랜턴 / 플래시",
                            PerAdultAmount = 0.5,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 15,
                            Category = "조명/전기",
                            Name = "릴선/작업선 (20m)",
                            PerAdultAmount = 0.20000000000000001,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 16,
                            Category = "조명/전기",
                            Name = "멀티탭",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 17,
                            Category = "조명/전기",
                            Name = "고용량 보조 배터리",
                            PerAdultAmount = 0.5,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 18,
                            Category = "취사도구",
                            Name = "휴대용 가스버너 (구이바다)",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 19,
                            Category = "취사도구",
                            Name = "부탄/이소가스",
                            PerAdultAmount = 1.0,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 20,
                            Category = "취사도구",
                            Name = "바베큐 화로대 & 그릴",
                            PerAdultAmount = 0.20000000000000001,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 21,
                            Category = "취사도구",
                            Name = "참숯 / 장작",
                            PerAdultAmount = 0.5,
                            Unit = "박스"
                        },
                        new
                        {
                            Id = 22,
                            Category = "취사도구",
                            Name = "캠핑 토치 (착화제 포함)",
                            PerAdultAmount = 0.20000000000000001,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 23,
                            Category = "취사도구",
                            Name = "코펠 세트 (냄비/팬)",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "세트"
                        },
                        new
                        {
                            Id = 24,
                            Category = "취사도구",
                            Name = "칼, 가위, 집게 세트",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "세트"
                        },
                        new
                        {
                            Id = 25,
                            Category = "취사도구",
                            Name = "국자, 뒤집개, 도마",
                            PerAdultAmount = 0.20000000000000001,
                            Unit = "세트"
                        },
                        new
                        {
                            Id = 26,
                            Category = "취사도구",
                            Name = "개인 식기 (밥/국그릇)",
                            PerAdultAmount = 1.0,
                            Unit = "세트"
                        },
                        new
                        {
                            Id = 27,
                            Category = "취사도구",
                            Name = "수저 세트",
                            PerAdultAmount = 1.0,
                            Unit = "세트"
                        },
                        new
                        {
                            Id = 28,
                            Category = "취사도구",
                            Name = "시에라 컵 / 텀블러",
                            PerAdultAmount = 1.0,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 29,
                            Category = "취사도구",
                            Name = "아이스박스 / 쿨러",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 30,
                            Category = "취사도구",
                            Name = "주방세제 및 수세미",
                            PerAdultAmount = 0.20000000000000001,
                            Unit = "세트"
                        },
                        new
                        {
                            Id = 31,
                            Category = "취사도구",
                            Name = "호일 / 키친타월",
                            PerAdultAmount = 0.20000000000000001,
                            Unit = "세트"
                        },
                        new
                        {
                            Id = 32,
                            Category = "식재료",
                            Name = "삼겹살",
                            PerAdultAmount = 200.0,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 33,
                            Category = "식재료",
                            Name = "목살",
                            PerAdultAmount = 150.0,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 34,
                            Category = "식재료",
                            Name = "가브리살/항정살",
                            PerAdultAmount = 100.0,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 35,
                            Category = "식재료",
                            Name = "살치살 (소고기)",
                            PerAdultAmount = 100.0,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 36,
                            Category = "식재료",
                            Name = "모듬 쌈야채 & 파채",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "팩"
                        },
                        new
                        {
                            Id = 37,
                            Category = "식재료",
                            Name = "구이용 소시지 / 치즈",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "팩"
                        },
                        new
                        {
                            Id = 38,
                            Category = "식재료",
                            Name = "봉지 / 컵라면",
                            PerAdultAmount = 1.5,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 39,
                            Category = "식재료",
                            Name = "햇반 / 즉석밥",
                            PerAdultAmount = 1.5,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 40,
                            Category = "식재료",
                            Name = "김치",
                            PerAdultAmount = 0.20000000000000001,
                            Unit = "팩"
                        },
                        new
                        {
                            Id = 41,
                            Category = "식재료",
                            Name = "소주 및 맥주",
                            PerAdultAmount = 3.0,
                            Unit = "병/캔"
                        },
                        new
                        {
                            Id = 42,
                            Category = "식재료",
                            Name = "생수 (2L)",
                            PerAdultAmount = 1.0,
                            Unit = "병"
                        },
                        new
                        {
                            Id = 43,
                            Category = "식재료",
                            Name = "음료수 / 토닉워터",
                            PerAdultAmount = 1.0,
                            Unit = "페트"
                        },
                        new
                        {
                            Id = 44,
                            Category = "위생용품",
                            Name = "대용량 물티슈",
                            PerAdultAmount = 0.29999999999999999,
                            Unit = "팩"
                        },
                        new
                        {
                            Id = 45,
                            Category = "위생용품",
                            Name = "두루마리 휴지",
                            PerAdultAmount = 0.5,
                            Unit = "롤"
                        },
                        new
                        {
                            Id = 46,
                            Category = "위생용품",
                            Name = "종량제 및 쓰레기봉투",
                            PerAdultAmount = 0.5,
                            Unit = "장"
                        },
                        new
                        {
                            Id = 47,
                            Category = "위생용품",
                            Name = "모기향 / 에프킬라 세트",
                            PerAdultAmount = 0.20000000000000001,
                            Unit = "세트"
                        },
                        new
                        {
                            Id = 48,
                            Category = "위생용품",
                            Name = "개인 세면도구 & 타월",
                            PerAdultAmount = 1.0,
                            Unit = "세트"
                        },
                        new
                        {
                            Id = 49,
                            Category = "의류/비상약",
                            Name = "여벌 옷 및 속옷/양말",
                            PerAdultAmount = 1.0,
                            Unit = "세트"
                        },
                        new
                        {
                            Id = 50,
                            Category = "의류/비상약",
                            Name = "방한 겉옷 (플리스/패딩)",
                            PerAdultAmount = 1.0,
                            Unit = "벌"
                        },
                        new
                        {
                            Id = 51,
                            Category = "의류/비상약",
                            Name = "캠핑용 편한 신발 (크록스)",
                            PerAdultAmount = 1.0,
                            Unit = "켤레"
                        },
                        new
                        {
                            Id = 52,
                            Category = "의류/비상약",
                            Name = "구급상자 (해열제/소화제/밴드)",
                            PerAdultAmount = 0.20000000000000001,
                            Unit = "세트"
                        });
                });

            modelBuilder.Entity("캠핑_정보_탐색_프로그램_V1.Models.Entity.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<int>("CampId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FavoriteId");

                    b.HasIndex("CampId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("캠핑_정보_탐색_프로그램_V1.Models.Entity.SearchHistory", b =>
                {
                    b.Property<int>("SearchHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SearchHistoryId"));

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("SearchHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("SearchHistories");
                });

            modelBuilder.Entity("캠핑_정보_탐색_프로그램_V1.Models.Entity.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("캠핑_정보_탐색_프로그램_V1.Models.Entity.Favorite", b =>
                {
                    b.HasOne("캠핑_정보_탐색_프로그램_V1.Models.Entity.Camp", "Camp")
                        .WithMany()
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camp");
                });

            modelBuilder.Entity("캠핑_정보_탐색_프로그램_V1.Models.Entity.SearchHistory", b =>
                {
                    b.HasOne("캠핑_정보_탐색_프로그램_V1.Models.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
